name: Say hello!
description: Say hello to the user.

on:
  workflow_dispatch:
    inputs:
      name:
        description: name of the person you are greeting
        required: true
        default: world

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
    - name: Say hello already
      run: echo hello ${{ inputs.name }}!
